"""Public diagram spec and spec generation surface."""

from __future__ import annotations

from .d2spec import (
    AnyNode,
    DecisionNode,
    DiagramSpec,
    Edge,
    FieldView,
    Group,
    ModelNode,
    ModuleNode,
    NodeRole,
    TerminalNode,
    entity_fields,
    field_default,
    is_entity,
    is_frozen,
    mentioned_types,
    type_str,
)
from .specgen import (
    AnySeedNode,
    AnySpecNode,
    AuthoredEdge,
    AuthoredExtra,
    BuiltPipelineProtocol,
    ChildFragment,
    DecisionOverlay,
    Overlay,
    SpecFragment,
    SpecgenLintError,
    StageSpecProtocol,
    TypeOverlay,
    TypeSource,
    fragment_from_pipeline,
    merge,
)

__all__ = [
    "AnyNode",
    "AnySeedNode",
    "AnySpecNode",
    "AuthoredEdge",
    "AuthoredExtra",
    "BuiltPipelineProtocol",
    "ChildFragment",
    "DecisionNode",
    "DecisionOverlay",
    "DiagramSpec",
    "Edge",
    "FieldView",
    "Group",
    "ModelNode",
    "ModuleNode",
    "NodeRole",
    "Overlay",
    "SpecFragment",
    "SpecgenLintError",
    "StageSpecProtocol",
    "TerminalNode",
    "TypeOverlay",
    "TypeSource",
    "entity_fields",
    "field_default",
    "fragment_from_pipeline",
    "is_entity",
    "is_frozen",
    "mentioned_types",
    "merge",
    "type_str",
]
