from __future__ import annotations

import pytest
from pydantic import BaseModel, ConfigDict, Field, computed_field

from vocab import (
    VocabDiff,
    VocabEntry,
    build_vocabulary,
    check_stale,
    diff_names,
    parse_tsv,
    pipeline_models,
    render_tsv,
    vocabulary_from_pipeline,
)


class Frozen(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")


class Base(Frozen):
    shared: int = Field(description="A value declared once on the base.")


class ChildInherits(Base):
    """Inherits `shared` without re-declaring it."""

    own: str


class ChildAlsoInherits(Base):
    """A second subclass that also inherits `shared`."""

    extra: float


class ChildRedeclares(Base):
    """Re-declares `shared` — a decllint violation, two owners for one name."""

    shared: int = Field(description="Re-declared on the child.")


class Nested(Frozen):
    tag: str


class Complex(Frozen):
    maybe: str | None
    items: list[Nested]
    ref: Nested
    pair: tuple[int, str]
    labelled: str = Field(description="Has a description.")


class LineItem(Frozen):
    sku: str = Field(description="Line item stock keeping unit.")


class Order(Frozen):
    items: list[LineItem]


class RootInput(Frozen):
    order_id: str


class PreparedOrder(Frozen):
    order: Order


class FinalSummary(Frozen):
    total_items: int

    @computed_field(description="Whether the order contains any line items.")
    @property
    def has_items(self) -> bool:
        return self.total_items > 0


class NestedPipelineOutput(Frozen):
    summary: FinalSummary


class ToyStage:
    output_type: type
    sub_pipeline: ToyPipeline | None

    def __init__(
        self, output_type: type, sub_pipeline: ToyPipeline | None = None
    ) -> None:
        self.output_type = output_type
        self.sub_pipeline = sub_pipeline


class ToyPipeline:
    root_types: tuple[type, ...]
    stages: tuple[ToyStage, ...]

    def __init__(
        self,
        root_types: tuple[type, ...] = (),
        stages: tuple[ToyStage, ...] = (),
    ) -> None:
        self.root_types = root_types
        self.stages = stages


def test_field_description_is_captured() -> None:
    entries = build_vocabulary([Complex])
    labelled = next(entry for entry in entries if entry.name == "labelled")
    assert labelled.description == "Has a description."
    maybe = next(entry for entry in entries if entry.name == "maybe")
    assert maybe.description == ""


def test_inherited_field_owned_by_base_and_emitted_once() -> None:
    entries = build_vocabulary([ChildInherits, ChildAlsoInherits])
    shared = [entry for entry in entries if entry.name == "shared"]
    assert len(shared) == 1
    assert shared[0].owner == "Base"
    assert shared[0].description == "A value declared once on the base."


def test_redeclared_field_emits_two_entries_with_different_owners() -> None:
    entries = build_vocabulary([Base, ChildRedeclares])
    shared = [entry for entry in entries if entry.name == "shared"]
    assert len(shared) == 2
    assert {entry.owner for entry in shared} == {"Base", "ChildRedeclares"}


def test_type_rendering_optional_list_union_and_nested_model() -> None:
    by_name = {entry.name: entry.type_name for entry in build_vocabulary([Complex])}
    assert by_name["maybe"] == "str | None"
    assert by_name["items"] == "list[Nested]"
    assert by_name["ref"] == "Nested"
    assert by_name["pair"] == "tuple[int, str]"


def test_deduplicates_shared_base_across_multiple_models() -> None:
    # Base reached via three different models must still yield one `shared` entry.
    entries = build_vocabulary([Base, ChildInherits, ChildAlsoInherits, ChildInherits])
    shared = [entry for entry in entries if entry.name == "shared"]
    assert len(shared) == 1


def test_render_parse_round_trip() -> None:
    entries = build_vocabulary([Complex, ChildInherits])
    text = render_tsv(entries)
    assert text.startswith("# vocabulary.tsv — generated by vocab.py, do not edit\n")
    assert text.endswith("\n")
    assert parse_tsv(text) == entries


def test_render_is_sorted_and_deterministic() -> None:
    forward = render_tsv(build_vocabulary([Complex, ChildInherits]))
    reversed_input = render_tsv(build_vocabulary([ChildInherits, Complex]))
    assert forward == reversed_input
    data_lines = [line for line in forward.splitlines() if not line.startswith("#")]
    names = [line.split("\t")[0] for line in data_lines]
    assert names == sorted(names)


def test_render_sanitizes_tabs_and_newlines_in_description() -> None:
    entry = VocabEntry(
        name="x",
        type_name="int",
        owner="M",
        description="line one\twith tab\nand newline",
    )
    text = render_tsv([entry])
    data_line = [line for line in text.splitlines() if not line.startswith("#")][0]
    assert data_line == "x\tint\tM\tline one with tab and newline"
    assert parse_tsv(text)[0].description == "line one with tab and newline"


def test_parse_ignores_comments_and_blank_lines() -> None:
    text = (
        "# a comment\n"
        "# name\ttype\towner\tdescription\n"
        "\n"
        "distance\tfloat\tTrip\tTotal trip distance\n"
    )
    entries = parse_tsv(text)
    assert entries == [
        VocabEntry(
            name="distance",
            type_name="float",
            owner="Trip",
            description="Total trip distance",
        )
    ]


def test_parse_tolerates_missing_description_column() -> None:
    entries = parse_tsv("distance\tfloat\tTrip\n")
    assert entries == [
        VocabEntry(name="distance", type_name="float", owner="Trip", description="")
    ]


def test_diff_names_reports_added_removed_and_changed() -> None:
    committed = [
        VocabEntry(name="alpha", type_name="int", owner="M", description="a"),
        VocabEntry(name="beta", type_name="int", owner="M", description="b"),
        VocabEntry(name="gamma", type_name="int", owner="M", description="c"),
    ]
    generated = [
        VocabEntry(name="alpha", type_name="int", owner="M", description="a"),
        VocabEntry(name="beta", type_name="str", owner="M", description="b"),
        VocabEntry(name="delta", type_name="int", owner="M", description="d"),
    ]
    diff = diff_names(committed, generated)
    assert diff == VocabDiff(added=("delta",), removed=("gamma",), changed=("beta",))


def test_diff_names_detects_owner_only_change() -> None:
    committed = [VocabEntry(name="x", type_name="int", owner="A")]
    generated = [VocabEntry(name="x", type_name="int", owner="B")]
    assert diff_names(committed, generated).changed == ("x",)


def test_diff_names_empty_when_identical() -> None:
    entries = build_vocabulary([Complex])
    assert diff_names(entries, entries) == VocabDiff()


def test_check_stale_true_when_committed_differs() -> None:
    stale_text = render_tsv([VocabEntry(name="old", type_name="int", owner="M")])
    assert check_stale(stale_text, [Complex]) is True


def test_check_stale_false_when_committed_matches() -> None:
    fresh_text = render_tsv(build_vocabulary([Complex]))
    assert check_stale(fresh_text, [Complex]) is False


def test_vocab_entry_is_frozen() -> None:
    entry = VocabEntry(name="x", type_name="int", owner="M")
    with pytest.raises(Exception):
        entry.name = "y"  # type: ignore[misc]


def test_pipeline_models_discovers_roots_stage_outputs_nested_pipelines_and_fields() -> (
    None
):
    child: ToyPipeline = ToyPipeline(
        stages=(
            ToyStage(output_type=NestedPipelineOutput),
            ToyStage(output_type=str),
        )
    )
    pipeline: ToyPipeline = ToyPipeline(
        root_types=(RootInput, int, BaseModel),
        stages=(
            ToyStage(output_type=PreparedOrder),
            ToyStage(output_type=list, sub_pipeline=child),
        ),
    )
    models: list[type[BaseModel]] = pipeline_models(pipeline)
    model_names: list[str] = [model.__name__ for model in models]
    assert model_names == sorted(model_names)
    assert model_names == [
        "FinalSummary",
        "LineItem",
        "NestedPipelineOutput",
        "Order",
        "PreparedOrder",
        "RootInput",
    ]
    assert len(models) == len(set(models))


def test_pipeline_models_discovers_model_reachable_only_through_field_annotation() -> (
    None
):
    pipeline: ToyPipeline = ToyPipeline(stages=(ToyStage(output_type=Order),))
    models: list[type[BaseModel]] = pipeline_models(pipeline)
    assert LineItem in models


def test_vocabulary_from_pipeline_includes_transitively_discovered_model_field() -> (
    None
):
    pipeline: ToyPipeline = ToyPipeline(stages=(ToyStage(output_type=Order),))
    entries: list[VocabEntry] = vocabulary_from_pipeline(pipeline)
    by_name: dict[str, VocabEntry] = {entry.name: entry for entry in entries}
    assert by_name["sku"] == VocabEntry(
        name="sku",
        type_name="str",
        owner="LineItem",
        description="Line item stock keeping unit.",
    )


def test_computed_field_description_is_captured() -> None:
    entries: list[VocabEntry] = vocabulary_from_pipeline(
        ToyPipeline(stages=(ToyStage(output_type=FinalSummary),))
    )
    by_name: dict[str, VocabEntry] = {entry.name: entry for entry in entries}
    assert by_name["has_items"].description == (
        "Whether the order contains any line items."
    )
