#!/usr/bin/env python3
"""Generate the pipeline's canonical vocabulary — every field name declared
across all entity models — as a build artifact.

This file is NEVER hand-maintained. `decllint` guarantees names are collision
free (one name is one quantity, declared once), which is what makes the generated
list a trustworthy *name registry* rather than an arbitrary dump. A committed copy
of the artifact lets CI diff it: when a PR introduces a NEW name the diff surfaces
it as the "registration gate" event, where an agent or human asks the only
question that matters — "is `speed` actually the existing `velocity`?".

The vocabulary attributes each field to the ONE class in the MRO that actually
declares it (same logic as `decllint.declaring_class`), so an inherited field is
owned by its declaring base and listed once, not repeated per subclass.

    from vocab import build_vocabulary, render_tsv, diff_names, check_stale
"""

from __future__ import annotations

from typing import Iterable

from pydantic import BaseModel, ConfigDict

from d2spec import entity_fields, type_str
from decllint import declaring_class

# The artifact is tab-separated with a two-line comment header. `#`-prefixed
# lines are metadata and are ignored on parse; every other line is one field.
TSV_HEADER: tuple[str, ...] = (
    "# vocabulary.tsv — generated by vocab.py, do not edit",
    "# name\ttype\towner\tdescription",
)
COMMENT_PREFIX = "#"
FIELD_SEPARATOR = "\t"
FIELD_COLUMNS = 4
# Descriptions are free text; tabs/newlines would break the row grid, so they
# collapse to single spaces on render.
_WHITESPACE_TO_SPACE = str.maketrans({"\t": " ", "\n": " ", "\r": " "})


class VocabEntry(BaseModel):
    """One field in the canonical vocabulary: its `name`, the human-readable
    `type_name` (e.g. "float", "list[Order]", "Order | None"), the `owner`
    (the single class in the MRO that declares it), and its `description`."""

    model_config = ConfigDict(frozen=True, extra="forbid")
    name: str
    type_name: str
    owner: str
    description: str = ""


class VocabDiff(BaseModel):
    """What the registration gate reviews between the committed artifact and a
    freshly generated one: names newly `added`, names `removed`, and names whose
    type/owner/description `changed`."""

    model_config = ConfigDict(frozen=True, extra="forbid")
    added: tuple[str, ...] = ()
    removed: tuple[str, ...] = ()
    changed: tuple[str, ...] = ()


def build_vocabulary(models: Iterable[type[BaseModel]]) -> list[VocabEntry]:
    """Every declared field across `models`, sorted by name, each appearing
    exactly once even when models inherit from each other or share a base.

    Deduplication is by (owner, name): an inherited field resolves to the same
    declaring base from every subclass, so it collapses to one entry. A field
    re-declared on a subclass resolves to a different owner, so it legitimately
    yields two entries — that is `decllint`'s violation to report, not ours; here
    we only keep the output deterministic.
    """
    by_key: dict[tuple[str, str], VocabEntry] = {}
    for model in models:
        for view in entity_fields(model):
            owner = declaring_class(model, view.name).__name__
            key = (owner, view.name)
            if key in by_key:
                continue
            by_key[key] = VocabEntry(
                name=view.name,
                type_name=type_str(view.annotation),
                owner=owner,
                description=view.description,
            )
    return sorted(by_key.values(), key=lambda entry: (entry.name, entry.owner))


def _sanitize(text: str) -> str:
    """Flatten any tab/newline in free text to spaces so it stays on one row."""
    return text.translate(_WHITESPACE_TO_SPACE)


def render_tsv(entries: Iterable[VocabEntry]) -> str:
    """Render entries as the stable TSV artifact: comment header, then one
    tab-separated row per entry, sorted by name, with a trailing newline."""
    ordered = sorted(entries, key=lambda entry: (entry.name, entry.owner))
    lines: list[str] = list(TSV_HEADER)
    for entry in ordered:
        lines.append(
            FIELD_SEPARATOR.join(
                (
                    _sanitize(entry.name),
                    _sanitize(entry.type_name),
                    _sanitize(entry.owner),
                    _sanitize(entry.description),
                )
            )
        )
    return "\n".join(lines) + "\n"


def parse_tsv(text: str) -> list[VocabEntry]:
    """Inverse of `render_tsv`: parse field rows back into entries, ignoring
    comment (`#`) and blank lines. A missing description column reads as ""."""
    entries: list[VocabEntry] = []
    for line in text.splitlines():
        if not line.strip() or line.startswith(COMMENT_PREFIX):
            continue
        columns = line.split(FIELD_SEPARATOR)
        # Pad a missing trailing description; ignore any extra columns.
        while len(columns) < FIELD_COLUMNS:
            columns.append("")
        name, type_name, owner, description = columns[:FIELD_COLUMNS]
        entries.append(
            VocabEntry(
                name=name,
                type_name=type_name,
                owner=owner,
                description=description,
            )
        )
    return entries


def _facets_by_name(entries: Iterable[VocabEntry]) -> dict[str, tuple[tuple[str, str, str], ...]]:
    """Map each name to the sorted tuple of its (type, owner, description)
    facets. A name usually maps to one facet; a name declared on two owners
    (a decllint violation) maps to two, compared deterministically."""
    grouped: dict[str, list[tuple[str, str, str]]] = {}
    for entry in entries:
        grouped.setdefault(entry.name, []).append(
            (entry.type_name, entry.owner, entry.description)
        )
    return {name: tuple(sorted(facets)) for name, facets in grouped.items()}


def diff_names(
    committed: list[VocabEntry], generated: list[VocabEntry]
) -> VocabDiff:
    """The registration-gate diff between the committed artifact and a freshly
    generated one, keyed by name: `added` names appear only in generated,
    `removed` only in committed, `changed` appear in both with a different
    type/owner/description."""
    committed_facets = _facets_by_name(committed)
    generated_facets = _facets_by_name(generated)
    added = tuple(sorted(generated_facets.keys() - committed_facets.keys()))
    removed = tuple(sorted(committed_facets.keys() - generated_facets.keys()))
    changed = tuple(
        sorted(
            name
            for name in committed_facets.keys() & generated_facets.keys()
            if committed_facets[name] != generated_facets[name]
        )
    )
    return VocabDiff(added=added, removed=removed, changed=changed)


def check_stale(committed_text: str, models: Iterable[type[BaseModel]]) -> bool:
    """CI freshness check: True when regenerating the vocabulary from `models`
    produces text that differs from `committed_text` (the artifact is stale)."""
    return render_tsv(build_vocabulary(models)) != committed_text


def _demo_models() -> list[type[BaseModel]]:
    """The demo models to describe: the entities from `demo_backends` if it
    imports cleanly, else a small self-contained example."""
    try:
        from demo_backends import Address, Customer, Order

        return [Address, Customer, Order]
    except Exception:

        class _DemoBase(BaseModel):
            model_config = ConfigDict(frozen=True)

        class Trip(_DemoBase):
            distance: float

        return [Trip]


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Cascade vocabulary generator.")
    parser.add_argument(
        "--demo",
        action="store_true",
        help="print the vocabulary of the demo models",
    )
    args = parser.parse_args()
    if args.demo:
        print(render_tsv(build_vocabulary(_demo_models())), end="")
    else:
        parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
